import 'dart:io';
import 'dart:ui';

List<String> lordGaneshaHindi =
[
"ॐ गजाननाय नमः।",
"ॐ गणाध्यक्षाय नमः।",
"ॐ विघ्नराजाय नमः।",
"ॐ विनायकाय नमः।",
"ॐ द्वैमातुराय नमः।",
"ॐ द्विमुखाय नमः।",
"ॐ प्रमुखाय नमः।",
"ॐ सुमुखाय नमः।",
"ॐ कृतिने नमः।",
"ॐ सुप्रदीपाय नमः।",
"ॐ सुखनिधये नमः।",
"ॐ सुराध्यक्षाय नमः।",
"ॐ सुरारिघ्नाय नमः।",
"ॐ महागणपतये नमः।",
"ॐ मान्याय नमः।",
"ॐ महाकालाय नमः।",
"ॐ महाबलाय नमः।",
"ॐ हेरम्बाय नमः।",
"ॐ लम्बजठरायै नमः।",
"ॐ ह्रस्व ग्रीवाय नमः।",
"ॐ महोदराय नमः।",
"ॐ मदोत्कटाय नमः।",
"ॐ महावीराय नमः।",
"ॐ मन्त्रिणे नमः।",
"ॐ मङ्गल स्वराय नमः।",
"ॐ प्रमधाय नमः।",
"ॐ प्रथमाय नमः।",
"ॐ प्राज्ञाय नमः।",
"ॐ विघ्नकर्त्रे नमः।",
"ॐ विघ्नहर्त्रे नमः।",
"ॐ विश्वनेत्रे नमः।",
"ॐ विराट्पतये नमः।",
"ॐ श्रीपतये नमः।",
"ॐ वाक्पतये नमः।",
"ॐ शृङ्गारिणे नमः।",
"ॐ अश्रितवत्सलाय नमः।",
"ॐ शिवप्रियाय नमः।",
"ॐ शीघ्रकारिणे नमः।",
"ॐ शाश्वताय नमः।",
"ॐ बल नमः।",
"ॐ बलोत्थिताय नमः।",
"ॐ भवात्मजाय नमः।",
"ॐ पुराण पुरुषाय नमः।",
"ॐ पूष्णे नमः।",
"ॐ पुष्करोत्षिप्त वारिणे नमः।",
"ॐ अग्रगण्याय नमः।",
"ॐ अग्रपूज्याय नमः।",
"ॐ अग्रगामिने नमः।",
"ॐ मन्त्रकृते नमः।",
"ॐ चामीकरप्रभाय नमः।",
"ॐ सर्वाय नमः।",
"ॐ सर्वोपास्याय नमः।",
"ॐ सर्व कर्त्रे नमः।",
"ॐ सर्वनेत्रे नमः।",
"ॐ सर्वसिद्धिप्रदाय नमः।",
"ॐ सिद्धये नमः।",
"ॐ पञ्चहस्ताय नमः।",
"ॐ पार्वतीनन्दनाय नमः।",
"ॐ प्रभवे नमः।",
"ॐ कुमारगुरवे नमः।",
"ॐ अक्षोभ्याय नमः।",
"ॐ कुञ्जरासुर भञ्जनाय नमः।",
"ॐ प्रमोदाय नमः।",
"ॐ मोदकप्रियाय नमः।",
"ॐ कान्तिमते नमः।",
"ॐ धृतिमते नमः।",
"ॐ कामिने नमः।",
"ॐ कपित्थपनसप्रियाय नमः।",
"ॐ ब्रह्मचारिणे नमः।",
"ॐ ब्रह्मरूपिणे नमः।",
"ॐ ब्रह्मविद्यादि दानभुवे नमः।",
"ॐ जिष्णवे नमः।",
"ॐ विष्णुप्रियाय नमः।",
"ॐ भक्त जीविताय नमः।",
"ॐ जितमन्मधाय नमः।",
"ॐ ऐश्वर्यकारणाय नमः।",
"ॐ ज्यायसे नमः।",
"ॐ यक्षकिन्नेर सेविताय नमः।",
"ॐ गङ्गा सुताय नमः।",
"ॐ गणाधीशाय नमः।",
"ॐ गम्भीर निनदाय नमः।",
"ॐ वटवे नमः।",
"ॐ अभीष्टवरदाय नमः।",
"ॐ ज्योतिषे नमः।",
"ॐ भक्तनिधये नमः।",
"ॐ भावगम्याय नमः।",
"ॐ मङ्गलप्रदाय नमः।",
"ॐ अव्यक्ताय नमः।",
"ॐ अप्राकृत पराक्रमाय नमः।",
"ॐ सत्यधर्मिणे नमः।",
"ॐ सखये नमः।",
"ॐ सरसाम्बुनिधये नमः।",
"ॐ महेशाय नमः।",
"ॐ दिव्याङ्गाय नमः।",
"ॐ मणिकिङ्किणी मेखालाय नमः।",
"ॐ समस्त देवता मूर्तये नमः।",
"ॐ सहिष्णवे नमः।",
"ॐ सततोत्थिताय नमः।",
"ॐ विघातकारिणे नमः।",
"ॐ विश्वग्दृशे नमः।",
"ॐ विश्वरक्षाकृते नमः।",
"ॐ कल्याणगुरवे नमः।",
"ॐ उन्मत्तवेषाय नमः।",
"ॐ अपराजिते नमः।",
"ॐ समस्त जगदाधाराय नमः।",
"ॐ सर्वैश्वर्यप्रदाय नमः।",
"ॐ आक्रान्त चिद चित्प्रभवे नमः।",
"ॐ श्री विघ्नेश्वराय नमः।",
];

List<String> lordGaneshaEnglish =
[
  "Om Gajananaya Namah।",
  "Om Ganadhyakshaya Namah।",
  "Om Vighnarajaya Namah।",
  "Om Vighnarajaya Namah।",
  "Om Dvaimaturaya Namah।",
  "Om Dwimukhaya Namah।",
  "Om Pramukhaya Namah।",
  "Om Sumukhaya Namah।",
  "Om Kritine Namah।",
  "Om Supradipaya Namah।",
  "Om Sukhanidhaye Namah।",
  "Om Suradhyakshaya Namah।",
  "Om Surarighnaya Namah।",
  "Om Mahaganapataye Namah।",
  "Om Manyaya Namah।",
  "Om Manyaya Namah।",
  "Om Mahabalaya Namah।",
  "Om Herambaya Namah।",
  "Om Lambajatharayai Namah।",
  "Om Haswa Grivaya Namah।",
  "Om Mahodaraya Namah।",
  "Om Madotkataya Namah।",
  "Om Mahaviraya Namah।",
  "Om Mantrine Namah।",
  "Om Mangala Swaraya Namah।",
  "Om Pramadhaya Namah।",
  "Om Prathamaya Namah।",
  "Om Prajnaya Namah।",
  "Om Vighnakartre Namah।",
  "Om Vignahartre Namah।",
  "Om Vishwanetre Namah।",
  "Om Viratpataye Namah।",
  "Om Shripataye Namah।",
  "Om Vakpataye Namah।",
  "Om Shringarine Namah।",
  "Om Ashritavatsalaya Namah।",
  "Om Shivapriyaya Namah।",
  "Om Shighrakarine Namah।",
  "Om Shashwataya Namah।",
  "Om Bala Namah।",
  "Om Balotthitaya Namah।",
  "Om Bhavatmajaya Namah।",
  "Om Purana Purushaya Namah।",
  "Om Pushne Namah।",
  "Om Pushkarotshipta Varine Namah।",
  "Om Agraganyaya Namah।",
  "Om Agrapujyaya Namah।",
  "Om Agragamine Namah।",
  "Om Mantrakrite Namah।",
  "Om Chamikaraprabhaya Namah।",
  "Om Sarvaya Namah।",
  "Om Sarvopasyaya Namah।",
  "Om Sarva Kartre Namah।",
  "Om Sarvanetre Namah।",
  "Om Sarvasiddhipradaya Namah।",
  "Om Siddhaye Namah।",
  "Om Panchahastaya Namah।",
  "Om Parvatinandanaya Namah।",
  "Om Prabhave Namah।",
  "Om Kumaragurave Namah।",
  "Om Akshobhyaya Namah।",
  "Om Kunjarasura Bhanjanaya Namah।",
  "Om Pramodaya Namah।",
  "Om Modakapriyaya Namah।",
  "Om Kantimate Namah।",
  "Om Dhritimate Namah।",
  "Om Kamine Namah।",
  "Om Kapitthapanasapriyaya Namah।",
  "Om Brahmacharine Namah।",
  "Om Brahmarupine Namah।",
  "Om Brahmavidyadi Danabhuve Namah।",
  "Om Jishnave Namah।",
  "Om Vishnupriyaya Namah।",
  "Om Bhakta Jivitaya Namah।",
  "Om Jitamanmadhaya Namah।",
  "Om Aishwaryakaranaya Namah।",
  "Om Jyayase Namah।",
  "Om Yaksha Kinnerasevitaya Namah।",
  "Om Ganga Sutaya Namah।",
  "Om Ganadhishaya Namah।",
  "Om Gambhira Ninadaya Namah।",
  "Om Vatave Namah।",
  "Om Abhishtavaradaya Namah।",
  "Om Jyotishe Namah।",
  "Om Bhktanidhaye Namah।",
  "Om Bhavagamyaya Namah।",
  "Om Mangalapradaya Namah।",
  "Om Avyaktaya Namah।",
  "Om Aprakrita Parakramaya Namah।",
  "Om Satyadharmine Namah।",
  "Om Sakhaye Namah।",
  "Om Sarasambunidhaye Namah।",
  "Om Maheshaya Namah।",
  "Om Divyangaya Namah।",
  "Om Manikinkini Mekhalaya Namah।",
  "Om Samasta Devata Murtaye Namah।",
  "Om Sahishnave Namah।",
  "Om Satatotthitaya Namah।",
  "Om Vighatakarine Namah।",
  "Om Vishwagdrishe Namah।",
  "Om Vishwarakshakrite Namah।",
  "Om Kalyanagurave Namah।",
  "Om Unmattaveshaya Namah।",
  "Om Aparajite Namah।",
  "Om Samsta Jagadadharaya Namah।",
  "Om Sarwaishwaryapradaya Namah।",
  "Om Akranta Chida Chitprabhave Namah।",
  "Om Shri Vighneshwaraya Namah।",
];

