List<String> goddessDurgaHindi = [
"ॐ श्रियै नमः।",
"ॐ उमायै नमः।",
"ॐ भारत्यै नमः।",
"ॐ भद्रायै नमः।",
"ॐ शर्वाण्यै नमः।",
"ॐ विजयायै नमः।",
"ॐ जयायै नमः।",
"ॐ वाण्यै नमः।",
"ॐ सर्वगतायै नमः।",
"ॐ गौर्यै नमः।",
"ॐ वाराह्यै नमः।",
"ॐ कमलप्रियायै नमः।",
"ॐ सरस्वत्यै नमः।",
"ॐ कमलायै नमः।",
"ॐ मायायै नमः।",
"ॐ मातंग्यै नमः।",
"ॐ अपरायै नमः।",
"ॐ अजायै नमः।",
"ॐ शांकभर्यै नमः।",
"ॐ शिवायै नमः।",
"ॐ चण्डयै नमः।",
"ॐ कुण्डल्यै नमः।",
"ॐ वैष्णव्यै नमः।",
"ॐ क्रियायै नमः।",
"ॐ श्रियै नमः।",
"ॐ ऐन्द्रयै नमः।",
"ॐ मधुमत्यै नमः।",
"ॐ गिरिजायै नमः।",
"ॐ सुभगायै नमः।",
"ॐ अंबिकायै नमः।",
"ॐ तारायै नमः।",
"ॐ पद्मावत्यै नमः।",
"ॐ हंसायै नमः।",
"ॐ पद्मनाभसहोदर्यै नमः।",
"ॐ अपर्णायै नमः।",
"ॐ ललितायै नमः।",
"ॐ धात्र्यै नमः।",
"ॐ कुमार्यै नमः।",
"ॐ शिखवाहिन्यै नमः।",
"ॐ शांभव्यै नमः।",
"ॐ सुमुख्यै नमः।",
"ॐ मैत्र्यै नमः।",
"ॐ त्रिनेत्रायै नमः।",
"ॐ विश्वरूपिण्यै नमः।",
"ॐ आर्यायै नमः।",
"ॐ मृडान्यै नमः।",
"ॐ हींकार्यै नमः।",
"ॐ क्रोधिन्यै नमः।",
"ॐ सुदिनायै नमः।",
"ॐ अचलायै नमः।",
"ॐ सूक्ष्मायै नमः।",
"ॐ परात्परायै नमः।",
"ॐ शोभायै नमः।",
"ॐ सर्ववर्णायै नमः।",
"ॐ हरप्रियायै नमः।",
"ॐ महालक्ष्म्यै नमः।",
"ॐ महासिद्धयै नमः।",
"ॐ स्वधायै नमः।",
"ॐ स्वाहायै नमः।",
"ॐ मनोन्मन्यै नमः।",
"ॐ त्रिलोकपालिन्यै नमः।",
"ॐ उद्भूतायै नमः।",
"ॐ त्रिसन्ध्यायै नमः।",
"ॐ त्रिपुरान्तक्यै नमः।",
"ॐ त्रिशक्त्यै नमः।",
"ॐ त्रिपदायै नमः।",
"ॐ दुर्गायै नमः।",
"ॐ ब्राह्मयै नमः।",
"ॐ त्रैलोक्यवासिन्यै नमः।",
"ॐ पुष्करायै नमः।",
"ॐ अत्रिसुतायै नमः।",
"ॐ गूढ़ायै नमः।",
"ॐ त्रिवर्णायै नमः।",
"ॐ त्रिस्वरायै नमः।",
"ॐ त्रिगुणायै नमः।",
"ॐ निर्गुणायै नमः।",
"ॐ सत्यायै नमः।",
"ॐ निर्विकल्पायै नमः।",
"ॐ निरंजिन्यै नमः।",
"ॐ ज्वालिन्यै नमः।",
"ॐ मालिन्यै नमः।",
"ॐ चर्चायै नमः।",
"ॐ क्रव्यादोप निबर्हिण्यै नमः।",
"ॐ कामाक्ष्यै नमः।",
"ॐ कामिन्यै नमः।",
"ॐ कान्तायै नमः।",
"ॐ कामदायै नमः।",
"ॐ कलहंसिन्यै नमः।",
"ॐ सलज्जायै नमः।",
"ॐ कुलजायै नमः।",
"ॐ प्राज्ञ्यै नमः।",
"ॐ प्रभायै नमः।",
"ॐ मदनसुन्दर्यै नमः।",
"ॐ वागीश्वर्यै नमः।",
"ॐ विशालाक्ष्यै नमः।",
"ॐ सुमंगल्यै नमः।",
"ॐ काल्यै नमः।",
"ॐ महेश्वर्यै नमः।",
"ॐ चण्ड्यै नमः।",
"ॐ भैरव्यै नमः।",
"ॐ भुवनेश्वर्यै नमः।",
"ॐ नित्यायै नमः।",
"ॐ सानन्दविभवायै नमः।",
"ॐ सत्यज्ञानायै नमः।",
"ॐ तमोपहायै नमः।",
"ॐ महेश्वरप्रियंकर्यै नमः।",
"ॐ महात्रिपुरसुन्दर्यै नमः।",
"ॐ दुर्गापरमेश्वर्यै नमः।"
];


List<String> goddessDurgaEnglish = [
  "Om sriyai namah ।",
  "Om umayai namah ।",
  "Om bharatyai namah ।",
  "Om bhadrayai namah ।",
  "Om sarvanyai namah ।",
  "Om vijayayai namah ।",
  "Om jayayai namah ।",
  "Om vanyai namah ।",
  "Om sarvagatayai namah ।",
  "Om gauryai namah ।",
  "Om varahyai namah ।",
  "Om kamalapriyayai namah ।",
  "Om sarasvatyai namah ।",
  "Om kamalayai namah ।",
  "Om mayayai namah ।",
  "Om matamgyai namah ।",
  "Om aparayai namah ।",
  "Om ajayai namah ।",
  "Om samkabharyai namah ।",
  "Om sivayai namah ।",
  "Om candayai namah ।",
  "Om kundalyai namah ।",
  "Om vaisnavyai namah ।",
  "Om kriyayai namah ।",
  "Om sriyai namah ।",
  "Om aindrayai namah ।",
  "Om madhumatyai namah ।",
  "Om girijayai namah ।",
  "Om subhagayai namah ।",
  "Om ambikayai namah ।",
  "Om tarayai namah ।",
  "Om padmavatyai namah ।",
  "Om hamsayai namah ।",
  "Om padmanabhasahodaryai namah ।",
  "Om aparnayai namah ।",
  "Om lalitayai namah ।",
  "Om dhatryai namah ।",
  "Om kumaryai namah ।",
  "Om sikhavahinyai namah ।",
  "Om sambhavyai namah ।",
  "Om sumukhyai namah ।",
  "Om maitryai namah ।",
  "Om trinetrayai namah ।",
  "Om visvarūpinyai namah ।",
  "Om aryayai namah ।",
  "Om mrdanyai namah ।",
  "Om hinkaryai namah ।",
  "Om krodhinyai namah ।",
  "Om sudinayai namah ।",
  "Om acalayai namah ।",
  "Om sūksmayai namah ।",
  "Om paratparayai namah ।",
  "Om sobhayai namah ।",
  "Om sarvavarnayai namah ।",
  "Om harapriyayai namah ।",
  "Om mahalaksmyai namah ।",
  "Om mahasiddhayai namah ।",
  "Om svadhayai namah ।",
  "Om svahayai namah ।",
  "Om manonmanyai namah ।",
  "Om trilokapalinyai namah ।",
  "Om udbhūtayai namah ।",
  "Om trisandhyayai namah ।",
  "Om tripurantakyai namah ।",
  "Om trisaktyai namah ।",
  "Om tripadayai namah ।",
  "Om durgayai namah ।",
  "Om brahmayai namah ।",
  "Om trailokyavasinyai namah ।",
  "Om puskarayai namah ।",
  "Om atrisutayai namah ।",
  "Om gūdha़ayai namah ।",
  "Om trivarnayai namah ।",
  "Om trisvarayai namah ।",
  "Om trigunayai namah ।",
  "Om nirgunayai namah ।",
  "Om satyayai namah ।",
  "Om nirvikalpayai namah ।",
  "Om niramjinyai namah ।",
  "Om jvalinyai namah ।",
  "Om malinyai namah ।",
  "Om carcayai namah ।",
  "Om kravyadopa nibarhinyai namah ।",
  "Om kamaksyai namah ।",
  "Om kaminyai namah ।",
  "Om kantayai namah ।",
  "Om kamadayai namah ।",
  "Om kalahamsinyai namah ।",
  "Om salajjayai namah ।",
  "Om kulajayai namah ।",
  "Om prajñyai namah ।",
  "Om prabhayai namah ।",
  "Om madanasundaryai namah ।",
  "Om vagisvaryai namah ।",
  "Om visalaksyai namah ।",
  "Om sumamgalyai namah ।",
  "Om kalyai namah ।",
  "Om mahesvaryai namah ।",
  "Om candyai namah ।",
  "Om bhairavyai namah ।",
  "Om bhuvanesvaryai namah ।",
  "Om nityayai namah ।",
  "Om sanandavibhavayai namah ।",
  "Om satyajñanayai namah ।",
  "Om tamopahayai namah ।",
  "Om mahesvarapriyankaryai namah ।",
  "Om mahatripurasundaryai namah ।",
  "Om durgaparamesvaryai namah ।"
];