List<String> lordKrishnaHindi = [
"ॐ कृष्णाय नमः।",
"ॐ कमलनाथाय नमः।",
"ॐ वासुदेवाय नमः।",
"ॐ सनातनाय नमः।",
"ॐ वसुदेवात्मजाय नमः।",
"ॐ पुण्याय नमः।",
"ॐ लीलामानुष विग्रहाय नमः।",
"ॐ श्रीवत्सकौस्तुभधराय नमः।",
"ॐ यशोदावत्सलाय नमः।",
"ॐ हरिये नमः।",
"ॐ चतुर्भुजात्तचक्रासिगदा नमः।",
"ॐ सङ्खाम्बुजायुदायुजाय नमः।",
"ॐ देवकीनन्दनाय नमः।",
"ॐ श्रीशाय नमः।",
"ॐ नन्दगोपप्रियात्मजाय नमः।",
"ॐ यमुनावेगासंहारिणे नमः।",
"ॐ बलभद्रप्रियनुजाय नमः।",
"ॐ पूतनाजीवितहराय नमः।",
"ॐ शकटासुरभञ्जनाय नमः।",
"ॐ नन्दव्रजजनानन्दिने नमः।",
"ॐ सच्चिदानन्दविग्रहाय नमः।",
"ॐ नवनीतविलिप्ताङ्गाय नमः।",
"ॐ नवनीतनटनाय नमः।",
"ॐ मुचुकुन्दप्रसादकाय नमः।",
"ॐ षोडशस्त्रीसहस्रेशाय नमः।",
"ॐ त्रिभङ्गिने नमः।",
"ॐ मधुराकृतये नमः।",
"ॐ शुकवागमृताब्दीन्दवे नमः।",
"ॐ गोविन्दाय नमः।",
"ॐ योगिनांपतये नमः।",
"ॐ वत्सवाटिचराय नमः।",
"ॐ अनन्ताय नमः।",
"ॐ धेनुकासुरभञ्जनाय नमः।",
"ॐ तृणीकृत तृणावर्ताय नमः।",
"ॐ यमलार्जुनभञ्जनाय नमः।",
"ॐ उत्तलोत्तालभेत्रे नमः।",
"ॐ तमालश्यामलाकृतिये नमः।",
"ॐ गोपगोपीश्वराय नमः।",
"ॐ योगिने नमः।",
"ॐ कोटिसूर्यसमप्रभाय नमः।",
"ॐ इलापतये नमः।",
"ॐ परंज्योतिषे नमः।",
"ॐ यादवेंद्राय नमः।",
"ॐ यदूद्वहाय नमः।",
"ॐ वनमालिने नमः।",
"ॐ पीतवसने नमः।",
"ॐ पारिजातापहारकाय नमः।",
"ॐ गोवर्थनाचलोद्धर्त्रे नमः।",
"ॐ गोपालाय नमः।",
"ॐ सर्वपालकाय नमः।",
"ॐ अजाय नमः।",
"ॐ निरञ्जनाय नमः।",
"ॐ कामजनकाय नमः।",
"ॐ कञ्जलोचनाय नमः।",
"ॐ मधुघ्ने नमः।",
"ॐ मथुरानाथाय नमः।",
"ॐ द्वारकानायकाय नमः।",
"ॐ बलिने नमः।",
"ॐ बृन्दावनान्त सञ्चारिणे नमः।",
"ॐ तुलसीदाम भूषनाय नमः।",
"ॐ स्यमन्तकमणेर्हर्त्रे नमः।",
"ॐ नरनारयणात्मकाय नमः।",
"ॐ कुब्जा कृष्णाम्बरधराय नमः।",
"ॐ मायिने नमः।",
"ॐ परमपुरुषाय नमः।",
"ॐ मुष्टिकासुर चाणूर मल्लयुद्ध विशारदाय नमः।",
"ॐ संसारवैरिणॆ नमः।",
"ॐ कंसारयॆ नमः।",
"ॐ मुरारयॆ नमः।",
"ॐ नाराकान्तकाय नमः।",
"ॐ अनादि ब्रह्मचारिणॆ नमः।",
"ॐ कृष्णाव्यसन कर्शकाय नमः।",
"ॐ शिशुपालशिरश्छेत्रे नमः।",
"ॐ दुर्यॊधनकुलान्तकाय नमः।",
"ॐ विदुराक्रूर वरदाय नमः।",
"ॐ विश्वरूपप्रदर्शकाय नमः।",
"ॐ सत्यवाचॆ नमः।",
"ॐ सत्य सङ्कल्पाय नमः।",
"ॐ सत्यभामारताय नमः।",
"ॐ जयिनॆ नमः।",
"ॐ सुभद्रा पूर्वजाय नमः।",
"ॐ विष्णवॆ नमः।",
"ॐ भीष्ममुक्ति प्रदायकाय नमः।",
"ॐ जगद्गुरवॆ नमः।",
"ॐ जगन्नाथाय नमः।",
"ॐ वॆणुनाद विशारदाय नमः।",
"ॐ वृषभासुर विध्वंसिने नमः।",
"ॐ बाणासुर करान्तकाय नमः।",
"ॐ युधिष्ठिर प्रतिष्ठात्रे नमः।",
"ॐ बर्हिबर्हावतंसकाय नमः।",
"ॐ पार्थसारथये नमः।",
"ॐ अव्यक्ताय नमः।",
"ॐ गीतामृत महोदधये नमः।",
"ॐ कालीय फणिमाणिक्य रञ्जित श्री पदाम्बुजाय नमः।",
"ॐ दामॊदराय नमः।",
"ॐ यज्ञभोक्त्रे नमः।",
"ॐ दानवॆन्द्र विनाशकाय नमः।",
"ॐ नारायणाय नमः।",
"ॐ परब्रह्मणॆ नमः।",
"ॐ पन्नगाशन वाहनाय नमः।",
"ॐ जलक्रीडा समासक्त गॊपीवस्त्रापहाराकाय नमः।",
"ॐ पुण्य श्लॊकाय नमः।",
"ॐ तीर्थकृते नमः।",
"ॐ वॆदवॆद्याय नमः।",
"ॐ दयानिधयॆ नमः।",
"ॐ सर्वभूतात्मकाय नमः।",
"ॐ सर्वग्रह रुपिणॆ नमः।",
"ॐ परात्पराय नमः।"
];

List<String> lordKrishnaEnglish = [

  "Om Krishnaya Namah।",
  "Om Kamalanathaya Namah।",
  "Om Vasudevaya Namah।",
  "Om Sanatanaya Namah।",
  "Om Vasudevatmajaya Namah।",
  "Om Punyaya Namah।",
  "Om Lilamanusha Vigrahaya Namah।",
  "Om Shrivatsakaustubhadharaya Namah।",
  "Om Yashodavatsalaya Namah।",
  "Om Hariye Namah।",
  "Om Chaturbhujattachakrasigada Namah।",
  "Om Sankhambujayudayujaya Namah।",
  "Om Devakinandanaya Namah।",
  "Om Shrishaya Namah।",
  "Om Nandagopapriyatmajaya Namah।",
  "Om Yamunavegasamharine Namah।",
  "Om Balabhadrapriyanujaya Namah।",
  "Om Putanajivitaharaya Namah।",
  "Om Shakatasurabhanjanaya Namah।",
  "Om Nandavrajajananandine Namah।",
  "Om Sachchidanandavigrahaya Namah।",
  "Om Navanitaviliptangaya Namah।",
  "Om Navanitanatanaya Namah।",
  "Om Muchukundaprasadakaya Namah।",
  "Om Shodashastrisahasreshaya Namah।",
  "Om Tribhangine Namah।",
  "Om Madhurakritaye Namah।",
  "Om Shukavagamritabdindave Namah।",
  "Om Govindaya Namah।",
  "Om Yoginampataye Namah।",
  "Om Vatsavaticharaya Namah।",
  "Om Anantaya Namah।",
  "Om Dhenukasurabhanjanaya Namah।",
  "Om Trinikrita Trinavartaya Namah।",
  "Om Yamalarjunabhanjanaya Namah।",
  "Om Uttalottalabhetre Namah।",
  "Om Tamalashyamalakritiye Namah।",
  "Om Gopagopishwaraya Namah।",
  "Om Yogine Namah।",
  "Om Kotisuryasamaprabhaya Namah।",
  "Om Ilapataye Namah।",
  "Om Paramjyotishe Namah।",
  "Om Yadavendraya Namah।",
  "Om Yadudvahaya Namah।",
  "Om Vanamaline Namah।",
  "Om Pitavasane Namah।",
  "Om Parijatapaharakaya Namah।",
  "Om Govarthanchalodhartreya Namah।",
  "Om Gopalaya Namah।",
  "Om Sarvapalakaya Namah।",
  "Om Ajaya Namah।",
  "Om Niranjanaya Namah।",
  "Om Kamajanakaya Namah।",
  "Om Kanjalochanaya Namah।",
  "Om Madhughne Namah।",
  "Om Mathuranathaya Namah।",
  "Om Dwarakanayakaya Namah।",
  "Om Baline Namah।",
  "Om Brindavananta Sancharine Namah।",
  "Om Tulasidama Bhushanaya Namah।",
  "Om Syamantakamarnerhartre Namah।",
  "Om Naranarayanatmakaya Namah।",
  "Om Kubja Krishnambaradharaya Namah।",
  "Om Mayine Namah।",
  "Om Paramapurushaya Namah।",
  "Om Mushtikasura Chanura Mallayuddha Visharadaya Namah।",
  "Om Sansaravairine Namah।",
  "Om Kamsaraye Namah।",
  "Om Muraraye Namah।",
  "Om Narakantakaya Namah।",
  "Om Anadi Brahmacharine Namah।",
  "Om Krishnavyasana Karshakaya Namah।",
  "Om Shishupalashirashchhetre Namah।",
  "Om Duryodhanakulantakaya Namah।",
  "Om Vidurakrura Varadaya Namah।",
  "Om Vishvarupapradarshakaya Namah।",
  "Om Satyavache Namah।",
  "Om Satya Sankalpaya Namah।",
  "Om Satyabhamarataya Namah।",
  "Om Jayine Namah।",
  "Om Subhadra Purvajaya Namah।",
  "Om Vishnave Namah।",
  "Om Bhishmamukti Pradayakaya Namah।",
  "Om Jagadgurave Namah।",
  "Om Jagannathaya Namah।",
  "Om Venunada Visharadaya Namah।",
  "Om Vrishabhasura Vidhvansine Namah।",
  "Om Banasura Karantakaya Namah।",
  "Om Yudhishthira Pratishthatre Namah।",
  "Om Barhibarhavatamsakaya Namah।",
  "Om Parthasarathaye Namah।",
  "Om Avyakta Namah।",
  "Om Gitamrita Mahodadhaye Namah।",
  "Om Kaliya Phanimanikya Ranjita Shri Padambujaya Namah।",
  "Om Damodaraya Namah।",
  "Om Yajnabhoktre Namah।",
  "Om Danavendra Vinashakaya Namah।",
  "Om Narayanaya Namah।",
  "Om Parabrahmane Namah।",
  "Om Pannagashana Vahanaya Namah।",
  "Om Jalakrida Samasakta Gopivastrapaharakaya Namah।",
  "Om Punya Shlokaya Namah।",
  "Om Tirthakrite Namah।",
  "Om Vedavedyaya Namah।",
  "Om Dayanidhaye Namah।",
  "Om Sarvabhutatmakaya Namah।",
  "Om Sarvagraha Rupine Namah।",
  "Om Paratparaya Namah।"

];