List<String> lordVenkateshHindi = [
"ૐ श्रीवॆंकटॆशाय नमः ।",
  "ૐ श्रीनिवासाय नमः ।",
  "ૐ लक्ष्मीपतयॆ नमः ।",
  "ૐ अनामयाय नमः ।",
  "ૐ अमृतांशाय नमः ।",
  "ૐ जगद्वंद्याय नमः ।",
  "ૐ गॊविंदाय नमः ।",
  "ૐ शाश्वताय नमः ।",
  "ૐ प्रभवॆ नमः ।",
  "ૐ शॆषाद्रिनिलयाय नमः ।",
  "ૐ दॆवाय नमः ।",
  "ૐ कॆशवाय नमः ।",
  "ૐ मधुसूदनाय नमः ।",
  "ૐ अमऋताय नमः ।",
  "ૐ माधवाय नमः ।",
  "ૐ कृष्णाय नमः ।",
  "ૐ श्रीहरयॆ नमः ।",
  "ૐ ज्ञानपंजराय नमः ।",
  "ૐ श्रीवत्सवक्षसॆ नमः ।",
  "ૐ सर्वॆशाय नमः ।",
  "ૐ गॊपालाय नमः ।",
  "ૐ पुरुषॊत्तमाय नमः ।",
  "ૐ गॊपीश्वराय नमः ।",
  "ૐ परंज्यॊतिषॆ नमः ।",
  "ૐ वैकुंठपतयॆ नमः ।",
  "ૐ अव्ययाय नमः ।",
  "ૐ सुधातनवॆ नमः ।",
  "ૐ यादवॆंद्राय नमः ।",
  "ૐ नित्ययौवनरूपवतॆ नमः ।",
  "ૐ चतुर्वॆदात्मकाय नमः ।",
  "ૐ विष्णवॆ नमः ।",
  "ૐ अच्युताय नमः ।",
  "ૐ पद्मिनीप्रियाय नमः ।",
  "ૐ धरापतयॆ नमः ।",
  "ૐ सुरपतयॆ नमः ।",
  "ૐ निर्मलाय नमः ।",
  "ૐ दॆवपूजिताय नमः ।",
  "ૐ चतुर्भुजाय नमः ।",
  "ૐ चक्रधराय नमः ।",
  "ૐ त्रिधाम्नॆ नमः ।",
  "ૐ त्रिगुणाश्रयाय नमः ।",
  "ૐ निर्विकल्पाय नमः ।",
  "ૐ निष्कळंकाय नमः ।",
  "ૐ निरातंकाय नमः ।",
  "ૐ निरंजनाय नमः ।",
  "ૐ निराभासाय नमः ।",
  "ૐ नित्यतृप्ताय नमः ।",
  "ૐ निर्गुणाय नमः ।",
  "ૐ निरुपद्रवाय नमः ।",
  "ૐ गदाधराय नमः ।",
  "ૐ शांग्रपाणयॆ नमः ।",
  "ૐ नंदकिनॆ नमः ।",
  "ૐ शंखदारकाय नमः ।",
  "ૐ अनॆकमूर्तयॆ नमः ।",
  "ૐ अव्यक्ताय नमः ।",
  "ૐ कटिहस्ताय नमः ।",
  "ૐ वरप्रदाय नमः ।",
  "ૐ अनॆकात्मनॆ नमः ।",
  "ૐ दीनबंधवॆ नमः ।",
  "ૐ आर्तलॊकाभयप्रदाय नमः ।",
  "ૐ आकाशराजवरदाय नमः ।",
  "ૐ यॊगिहृत्पद्ममंदिराय नमः ।",
  "ૐ दामॊदराय नमः ।",
  "ૐ जगत्पालाय नमः ।",
  "ૐ पापघ्नाय नमः ।",
  "ૐ भक्तवत्सलाय नमः ।",
  "ૐ त्रिविक्रमाय नमः ।",
  "ૐ शिंशुमाराय नमः ।",
  "ૐ जटामुकुटशॊभिताय नमः ।",
  "ૐ शंखमध्यॊल्लसन्मंजुलकिंकिण्याढ्यकरंडकाय नमः ।",
  "ૐ नीलमॆघश्यामतनवॆ नमः ।",
  "ૐ बिल्वपत्रार्चन प्रियाय नमः ।",
  "ૐ जगद्व्यापिनॆ नमः ।",
  "ૐ जगत्कर्त्रॆ नमः ।",
  "ૐ जगत्साक्षिणॆ नमः ।",
  "ૐ जगत्पतयॆ नमः ।",
  "ૐ चिंतितार्थ प्रदायकाय नमः ।",
  "ૐ जिष्णवॆ नमः ।",
  "ૐ दाशार्हाय नमः ।",
  "ૐ दशरूपवतॆ नमः ।",
  "ૐ दॆवकीनंदनाय नमः ।",
  "ૐ शौरयॆ नमः ।",
  "ૐ हयग्रीवाय नमः ।",
  "ૐ जनार्दनाय नमः ।",
  "ૐ कन्याश्रवणतारॆज्याय नमः ।",
  "ૐ पीतांबरधराय नमः ।",
  "ૐ अनघाय नमः ।",
  "ૐ वनमालिनॆ नमः ।",
  "ૐ पद्मनाभाय नमः ।",
  "ૐ मृगयासक्तमानसाय नमः ।",
  "ૐ अश्वारूढाय नमः ।",
  "ૐ खड्गधारिणॆ नमः ।",
  "ૐ धनार्जनसुमुत्सुकाय नमः ।",
  "ૐ घनसारलसन्मध्यत कस्तूरीतिलकॊज्ज्वलाय नमः ।",
  "ૐ सच्चिदानंदरूपाय नमः ।",
  "ૐ जगन्मंगळदायकाय नमः ।",
  "ૐ यज्ञरूपाय नमः ।",
  "ૐ यज्ञभॊक्त्रॆ नमः ।",
  "ૐ चिन्मयाय नमः ।",
  "ૐ परमॆश्वराय नमः ।",
  "ૐ परमार्थप्रदायकाय नमः ।",
  "ૐ शांताय नमः ।",
  "ૐ श्रीमतॆ नमः ।",
  "ૐ दॊर्दंडविक्रमाय नमः ।",
  "ૐ परात्पराय नमः ।",
  "ૐ परब्रह्मणॆ नमः ।",
  "ૐ श्री विभवॆ नमः ।",
  "ૐ जगदॆश्वराय नमः ।",
];

List<String> lordVenkateshEnglish = [

  "om sri venkatesaya namah।",
  "om srinivasaya namah।",
  "om laksmipataye namah।",
  "om ananuyaya namah।",
  "om amrtamsane namah।",
  "om madhavaya namah।",
  "om krsnaya namah।",
  "om sriharaye namah।",
  "om nnanapanjaraya namah।",
  "om srivatsa vaksase namah।",
  "om jagadvandyaya namah।",
  "om govindaya namah।",
  "om sasvataya namah।",
  "om prabhave namah।",
  "om sesadrinilayaya namah।",
  "om devaya namah।",
  "om kesavaya namah।",
  "om madhusudanaya namah।",
  "om amrtaya namah।",
  "om visnave namah।",
  "om acyutaya namah।",
  "om padminipriyaya namah।",
  "om sarvesaya namah।",
  "om gopalaya namah।",
  "om purusottamaya namah।",
  "om gopisvaraya namah।",
  "om paranjyotise namah।",
  "om vtekuntha pataye namah।",
  "om avyayaya namah।",
  "om sudhatanave namah।",
  "om yada vendraya namah।",
  "om nitya yauvanarupavate namah।",
  "om niranjanaya namah।",
  "om virabhasaya namah।",
  "om nitya trpttaya namah।",
  "om dharapataye namah।",
  "om surapataye namah।",
  "om nirmalaya namah।",
  "om devapujitaya namah।",
  "om caturbhujaya namah।",
  "om cakradharaya namah।",
  "om caturvedatmakaya namah।",
  "om tridhamne namah।",
  "om trigunasrayaya namah।",
  "om nirvikalpaya namah।",
  "om niskaḷankaya namah।",
  "om nirantakaya namah।",
  "om artalokabhayapradaya namah।",
  "om nirupradavaya namah।",
  "om nirgunaya namah।",
  "om gadadharaya namah।",
  "om sarnnapanaye namah।",
  "om nandakini namah।",
  "om sankhadarakaya namah।",
  "om anekamurtaye namah।",
  "om avyaktaya namah।",
  "om katihastaya namah।",
  "om varapradaya namah।",
  "om anekatmane namah।",
  "om dinabandhave namah।",
  "om jagadvyapine namah।",
  "om akasarajavaradaya namah।",
  "om yogihrtpadsamandiraya namah।",
  "om damodaraya namah।",
  "om jagatpalaya namah।",
  "om papaghnaya namah।",
  "om bhaktavatsalaya namah।",
  "om trivikramaya namah।",
  "om simsumaraya namah।",
  "om jatamakuta sobhitaya namah।",
  "om sankha madyolla sanmanju kinkinyadhya namah।",
  "om karundakaya namah।",
  "om nilamoghasyama tanave namah।",
  "om bilvapattrarcana priyaya namah।",
  "om jagatkartre namah।",
  "om jagatsaksine namah।",
  "om jagatpataye namah।",
  "om cintitardha pradayakaya namah।",
  "om jisnave namah।",
  "om dasarhaya namah।",
  "om dasarupavate namah।",
  "om devaki nandanaya namah।",
  "om sauraye namah।",
  "om hayarivaya namah।",
  "om janardhanaya namah।",
  "om kanyasranatarejyaya namah।",
  "om pitambaradharaya namah।",
  "om anaghaya namah।",
  "om vanamaline namah।",
  "om padmanabhaya namah।",
  "om mrgayasakta manasaya namah।",
  "om asvarudhaya namah।",
  "om khadgadharine namah।",
  "om dhanarjana samutsukaya namah।",
  "om ghanatarala sanmadhyakasturi tilakojjvalaya namah।",
  "om saccitanandarupaya namah।",
  "om jaganmangaḷa dayakaya namah।",
  "om yannabhokre namah।",
  "om cinmayaya namah।",
  "om paramesvaraya namah।",
  "om paramardhapradayakaya namah।",
  "om santaya namah।",
  "om srimate namah।",
  "om dordanda vikramaya namah।",
  "om parabrahmane namah।",
  "om srivibhave namah।",
  "om jagadisvaraya namah।"

];