List<String> lordHanumanHindi = [
"ॐ आञ्जनेयाय नमः।",
"ॐ महावीराय नमः।",
"ॐ हनूमते नमः।",
"ॐ मारुतात्मजाय नमः।",
"ॐ तत्वज्ञानप्रदाय नमः।",
"ॐ सीतादेविमुद्राप्रदायकाय नमः।",
"ॐ अशोकवनकाच्छेत्रे नमः।",
"ॐ सर्वमायाविभंजनाय नमः।",
"ॐ सर्वबन्धविमोक्त्रे नमः।",
"ॐ रक्षोविध्वंसकारकाय नमः।",
"ॐ परविद्या परिहाराय नमः।",
"ॐ परशौर्य विनाशनाय नमः।",
"ॐ परमन्त्र निराकर्त्रे नमः।",
"ॐ परयन्त्र प्रभेदकाय नमः।",
"ॐ सर्वग्रह विनाशिने नमः।",
"ॐ भीमसेन सहायकृथे नमः।",
"ॐ सर्वदुखः हराय नमः।",
"ॐ सर्वलोकचारिणे नमः।",
"ॐ मनोजवाय नमः।",
"ॐ पारिजात द्रुमूलस्थाय नमः।",
"ॐ सर्वमन्त्र स्वरूपवते नमः।",
"ॐ सर्वतन्त्र स्वरूपिणे नमः।",
"ॐ सर्वयन्त्रात्मकाय नमः।",
"ॐ कपीश्वराय नमः।",
"ॐ महाकायाय नमः।",
"ॐ सर्वरोगहराय नमः।",
"ॐ प्रभवे नमः।",
"ॐ बल सिद्धिकराय नमः।",
"ॐ सर्वविद्या सम्पत्तिप्रदायकाय नमः।",
"ॐ कपिसेनानायकाय नमः।",
"ॐ भविष्यथ्चतुराननाय नमः।",
"ॐ कुमार ब्रह्मचारिणे नमः।",
"ॐ रत्नकुण्डल दीप्तिमते नमः।",
"ॐ चञ्चलद्वाल सन्नद्धलम्बमान शिखोज्वलाय नमः।",
"ॐ गन्धर्व विद्यातत्वज्ञाय नमः।",
"ॐ महाबल पराक्रमाय नमः।",
"ॐ काराग्रह विमोक्त्रे नमः।",
"ॐ शृन्खला बन्धमोचकाय नमः।",
"ॐ सागरोत्तारकाय नमः।",
"ॐ प्राज्ञाय नमः।",
"ॐ रामदूताय नमः।",
"ॐ प्रतापवते नमः।",
"ॐ वानराय नमः।",
"ॐ केसरीसुताय नमः।",
"ॐ सीताशोक निवारकाय नमः।",
"ॐ अन्जनागर्भ सम्भूताय नमः।",
"ॐ बालार्कसद्रशाननाय नमः।",
"ॐ विभीषण प्रियकराय नमः।",
"ॐ दशग्रीव कुलान्तकाय नमः।",
"ॐ लक्ष्मणप्राणदात्रे नमः।",
"ॐ वज्रकायाय नमः।",
"ॐ महाद्युथये नमः।",
"ॐ चिरञ्जीविने नमः।",
"ॐ रामभक्ताय नमः।",
"ॐ दैत्यकार्य विघातकाय नमः।",
"ॐ अक्षहन्त्रे नमः।",
"ॐ काञ्चनाभाय नमः।",
"ॐ पञ्चवक्त्राय नमः।",
"ॐ महातपसे नमः।",
"ॐ लन्किनी भञ्जनाय नमः।",
"ॐ श्रीमते नमः।",
"ॐ सिंहिकाप्राण भञ्जनाय नमः।",
"ॐ गन्धमादन शैलस्थाय नमः।",
"ॐ लङ्कापुर विदायकाय नमः।",
"ॐ सुग्रीव सचिवाय नमः।",
"ॐ धीराय नमः।",
"ॐ शूराय नमः।",
"ॐ दैत्यकुलान्तकाय नमः।",
"ॐ सुरार्चिताय नमः।",
"ॐ महातेजसे नमः।",
"ॐ रामचूडामणिप्रदायकाय नमः।",
"ॐ कामरूपिणे नमः।",
"ॐ पिङ्गलाक्षाय नमः।",
"ॐ वार्धिमैनाक पूजिताय नमः।",
"ॐ कबळीकृत मार्ताण्डमण्डलाय नमः।",
"ॐ विजितेन्द्रियाय नमः।",
"ॐ रामसुग्रीव सन्धात्रे नमः।",
"ॐ महारावण मर्धनाय नमः।",
"ॐ स्फटिकाभाय नमः।",
"ॐ वागधीशाय नमः।",
"ॐ नवव्याकृतपण्डिताय नमः।",
"ॐ चतुर्बाहवे नमः।",
"ॐ दीनबन्धुराय नमः।",
"ॐ मायात्मने नमः।",
"ॐ भक्तवत्सलाय नमः।",
"ॐ संजीवननगायार्था नमः।",
"ॐ सुचये नमः।",
"ॐ वाग्मिने नमः।",
"ॐ दृढव्रताय नमः।",
"ॐ कालनेमि प्रमथनाय नमः।",
"ॐ हरिमर्कट मर्कटाय नमः।",
"ॐ दान्ताय नमः।",
"ॐ शान्ताय नमः।",
"ॐ प्रसन्नात्मने नमः।",
"ॐ शतकन्टमुदापहर्त्रे नमः।",
"ॐ योगिने नमः।",
"ॐ रामकथा लोलाय नमः।",
"ॐ सीतान्वेषण पण्डिताय नमः।",
"ॐ वज्रद्रनुष्टाय नमः।",
"ॐ वज्रनखाय नमः।",
"ॐ रुद्र वीर्य समुद्भवाय नमः।",
"ॐ इन्द्रजित्प्रहितामोघब्रह्मास्त्र विनिवारकाय नमः।",
"ॐ पार्थ ध्वजाग्रसंवासिने नमः।",
"ॐ शरपञ्जर भेदकाय नमः।",
"ॐ दशबाहवे नमः।",
"ॐ लोकपूज्याय नमः।",
"ॐ जाम्बवत्प्रीतिवर्धनाय नमः।",
"ॐ सीतासमेत श्रीरामपाद सेवदुरन्धराय नमः।"

];

List<String> lordHanumanEnglish = [
  "Om Anjaneyaya Namah।",
  "Om Mahaviraya Namah।",
  "Om Hanumate Namah।",
  "Om Marutatmajaya Namah।",
  "Om Tatvajnanapradaya Namah।",
  "Om Sitadevimudrapradayakaya Namah।",
  "Om Ashokavanakachchhetre Namah।",
  "Om Sarvamayavibhanjanaya Namah।",
  "Om Sarvabandhavimoktre Namah।",
  "Om Rakshovidhwansakarakaya Namah।",
  "Om Paravidya Pariharaya Namah।",
  "Om Parashaurya Vinashanaya Namah।",
  "Om Paramantra Nirakartre Namah।",
  "Om Parayantra Prabhedakaya Namah।",
  "Om Sarvagraha Vinashine Namah।",
  "Om Bhimasena Sahayakrithe Namah।",
  "Om Sarvadukha Haraya Namah।",
  "Om Sarvalokacharine Namah।",
  "Om Manojavaya Namah।",
  "Om Parijata Drumulasthaya Namah।",
  "Om Sarvamantra Swarupavate Namah।",
  "Om Sarvatantra Swarupine Namah।",
  "Om Sarvayantratmakaya Namah।",
  "Om Kapishwaraya Namah।",
  "Om Mahakayaya Namah।",
  "Om Sarvarogaharaya Namah।",
  "Om Prabhave Namah।",
  "Om Bala Siddhikaraya Namah।",
  "Om Sarvavidya Sampattipradayakaya Namah।",
  "Om Kapisenanayakaya Namah।",
  "Om Bhavishyathchaturananaya Namah।",
  "Om Kumara Brahmacharine Namah।",
  "Om Ratnakundala Diptimate Namah।",
  "Om Chanchaladwala Sannaddhalambamana Shikhojwala Namah।",
  "Om Gandharva Vidyatatvajnaya Namah।",
  "Om Mahabala Parakramaya Namah।",
  "Om Karagraha Vimoktre Namah।",
  "Om Shrinkhala Bandhamochakaya Namah।",
  "Om Sagarottarakaya Namah।",
  "Om Prajnaya Namah।",
  "Om Ramadutaya Namah।",
  "Om Pratapavate Namah।",
  "Om Vanaraya Namah।",
  "Om Kesarisutaya Namah।",
  "Om Sitashoka Nivarakaya Namah।",
  "Om Anjanagarbha Sambhutaya Namah।",
  "Om Balarkasadrashananaya Namah।",
  "Om Vibhishana Priyakaraya Namah।",
  "Om Dashagriva Kulantakaya Namah।",
  "Om Lakshmanapranadatre Namah।",
  "Om Vajrakayaya Namah।",
  "Om Mahadyuthaye Namah।",
  "Om Chiranjivine Namah।",
  "Om Ramabhaktaya Namah।",
  "Om Daityakarya Vighatakaya Namah।",
  "Om Akshahantre Namah।",
  "Om Kanchanabhaya Namah।",
  "Om Panchavaktraya Namah।",
  "Om Mahatapase Namah।",
  "Om Lankini Bhanjanaya Namah।",
  "Om Shrimate Namah।",
  "Om Simhikaprana Bhanjanaya Namah।",
  "Om Gandhamadana Shailasthaya Namah।",
  "Om Lankapura Vidayakaya Namah।",
  "Om Sugriva Sachivaya Namah।",
  "Om Dhiraya Namah।",
  "Om Shuraya Namah।",
  "Om Daityakulantakaya Namah।",
  "Om Surarchitaya Namah।",
  "Om Mahatejase Namah।",
  "Om Ramachudamanipradayakaya Namah।",
  "Om Kamarupine Namah।",
  "Om Pingalakshaya Namah।",
  "Om Vardhimainaka Pujitaya Namah।",
  "Om Kabalikrita Martandamandalaya Namah।",
  "Om Vijitendriyaya Namah।",
  "Om Ramasugriva Sandhatre Namah।",
  "Om Maharavana Mardhanaya Namah।",
  "Om Sphatikabhaya Namah।",
  "Om Vagadhishaya Namah।",
  "Om Navavyakritapanditaya Namah।",
  "Om Chaturbahave Namah।",
  "Om Dinabandhuraya Namah।",
  "Om Mayatmane Namah।",
  "Om Bhaktavatsalaya Namah।",
  "Om Sanjivananagayartha Namah।",
  "Om Suchaye Namah।",
  "Om Vagmine Namah।",
  "Om Dridhavrataya Namah।",
  "Om Kalanemi Pramathanaya Namah।",
  "Om Harimarkata Markataya Namah।",
  "Om Dantaya Namah।",
  "Om Shantaya Namah।",
  "Om Prasannatmane Namah।",
  "Om Shatakantamudapahartre Namah।",
  "Om Yogine Namah।",
  "Om Ramakatha Lolaya Namah।",
  "Om Sitanveshana Panditaya Namah।",
  "Om Vajradranushtaya Namah।",
  "Om Vajranakhaya Namah।",
  "Om Rudra Virya Samudbhavaya Namah।",
  "Om Indrajitprahitamoghabrahmastra Vinivarakaya Namah।",
  "Om Partha Dhwajagrasamvasine Namah।",
  "Om Sharapanjara Bhedakaya Namah।",
  "Om Dashabahave Namah।",
  "Om Lokapujyaya Namah।",
  "Om Jambavatpritivardhanaya Namah।",
  "Om Sitasameta Shriramapada sevadurandharaya Namah।"

];