List<String> lordSubHindi = [
"ॐ स्कन्दाय नमः",
"ॐ गुहाय नमः",
"ॐ षण्मुखाय नमः",
"ॐ फालनेत्र सुताय नमः",
"ॐ प्रभवे नमः",
"ॐ पिङ्गलाय नमः",
"ॐ क्रुत्तिकासूनवे नमः",
"ॐ सिखिवाहाय नमः",
"ॐ द्विनादभुजाय नमः",
"ॐ द्विषन्णे त्राय नमः",
"ॐ शक्तिधराय नमः",
"ॐ फिशिताश प्रभञ्जनाय नमः",
"ॐ तारकासुर संहार्त्रे नमः",
"ॐ रक्षोबलविमर्द नाय नमः",
"ॐ मत्ताय नमः",
"ॐ प्रमत्ताय नमः",
"ॐ उन्मत्ताय नमः",
"ॐ सुरसैन्य स्सुरक्ष काय नमः",
"ॐ दीवसेनापतये नमः",
"ॐ प्राज्ञाय नमः",
"ॐ कृपालवे नमः",
"ॐ भक्तवत्सलाय नमः",
"ॐ उमासुताय नमः",
"ॐ शक्तिधराय नमः",
"ॐ कुमाराय नमः",
"ॐ क्रौञ्च दारणाय नमः",
"ॐ सेनानिये नमः",
"ॐ अग्निजन्मने नमः",
"ॐ विशाखाय नमः",
"ॐ शङ्करात्मजाय नमः",
"ॐ शिवस्वामिने नमः",
"ॐ गुण स्वामिने नमः",
"ॐ सर्वस्वामिने नमः",
"ॐ सनातनाय नमः",
"ॐ अनन्त शक्तिये नमः",
"ॐ अक्षोभ्याय नमः",
"ॐ पार्वतिप्रियनन्दनाय नमः",
"ॐ गङ्गासुताय नमः",
"ॐ सरोद्भूताय नमः",
"ॐ अहूताय नमः",
"ॐ पावकात्मजाय नमः",
"ॐ ज्रुम्भाय नमः",
"ॐ प्रज्रुम्भाय नमः",
"ॐ उज्ज्रुम्भाय नमः",
"ॐ कमलासन संस्तुताय नमः",
"ॐ एकवर्णाय नमः",
"ॐ द्विवर्णाय नमः",
"ॐ त्रिवर्णाय नमः",
"ॐ सुमनोहराय नमः",
"ॐ चतुर्व र्णाय नमः",
"ॐ पञ्च वर्णाय नमः",
"ॐ प्रजापतये नमः",
"ॐ आहार्पतये नमः",
"ॐ अग्निगर्भाय नमः",
"ॐ शमीगर्भाय नमः",
"ॐ विश्वरेतसे नमः",
"ॐ सुरारिघ्ने नमः",
"ॐ हरिद्वर्णाय नमः",
"ॐ शुभकाराय नमः",
"ॐ वटवे नमः",
"ॐ वटवेष भ्रुते नमः",
"ॐ पूषाय नमः",
"ॐ गभस्तिये नमः",
"ॐ गहनाय नमः",
"ॐ चन्द्रवर्णाय नमः",
"ॐ कलाधराय नमः",
"ॐ मायाधराय नमः",
"ॐ महामायिने नमः",
"ॐ कैवल्याय नमः",
"ॐ शङ्करात्मजाय नमः",
"ॐ विस्वयोनिये नमः",
"ॐ अमेयात्मा नमः",
"ॐ तेजोनिधये नमः",
"ॐ अनामयाय नमः",
"ॐ परमेष्टिने नमः",
"ॐ परब्रह्मय नमः",
"ॐ वेदगर्भाय नमः",
"ॐ विराट्सुताय नमः",
"ॐ पुलिन्दकन्याभर्ताय नमः",
"ॐ महासार स्वताव्रुताय नमः",
"ॐ आश्रित खिलदात्रे नमः",
"ॐ चोरघ्नाय नमः",
"ॐ रोगनाशनाय नमः",
"ॐ अनन्त मूर्तये नमः",
"ॐ आनन्दाय नमः",
"ॐ शिखिण्डिकृत केतनाय नमः",
"ॐ डम्भाय नमः",
"ॐ परम डम्भाय नमः",
"ॐ महा डम्भाय नमः",
"ॐ क्रुपाकपये नमः",
"ॐ कारणोपात्त देहाय नमः",
"ॐ कारणातीत विग्रहाय नमः",
"ॐ अनीश्वराय नमः",
"ॐ अमृताय नमः",
"ॐ प्राणाय नमः",
"ॐ प्राणायाम पारायणाय नमः",
"ॐ विरुद्दहन्त्रे नमः",
"ॐ वीरघ्नाय नमः",
"ॐ रक्तास्याय नमः",
"ॐ श्याम कन्धराय नमः",
"ॐ सुब्र ह्मण्याय नमः",
"ॐ आन् गुहाय नमः",
"ॐ प्रीताय नमः",
"ॐ ब्राह्मण्याय नमः",
"ॐ ब्राह्मण प्रियाय नमः",
"ॐ वेदवेद्याय नमः",
"ॐ अक्षय फलदाय नमः",
"ॐ वल्ली देवसेना समेत श्री सुब्रह्मण्य स्वामिने नमः"
];


List<String> lordSubEnglish = [
  "Om Skandaya namaha",
  "Om Guhaya namaha",
  "Om Shanmukhaya namaha",
  "Om Balanetrasutaya namaha",
  "Om Prabhave namaha",
  "Om Pingalaya namaha",
  "Om Krittikasunave namaha",
  "Om Sikhivahanaya namaha",
  "Om Dvinadbhujaya namaha",
  "Om Dvinannetraya namaha",
  "Om Saktidharaya namaha",
  "Om Pisidasaprabhajanaya namaha",
  "Om Tarakasurasamharine namaha",
  "Om Raksobalavimardanaya namaha",
  "Om Mattaya namaha",
  "Om Pramattaya namaha",
  "Om Unmattaya namaha",
  "Om Surasainyasuraksakaya namaha",
  "Om Devasenapataye namaha",
  "Om Pragnya namaha",
  "Om Kripalave namaha",
  "Om Bhaktavatsalaya namaha",
  "Om Umasutaya namaha",
  "Om Saktidharaya namaha",
  "Om Kumaraya namaha",
  "Om Krauncadharanaya namaha",
  "Om Senanye namaha",
  "Om Agnijanmane namaha",
  "Om Visakhaya namaha",
  "Om Shankaratmajaya namaha",
  "Om Sivasvamine namaha",
  "Om Ganaswamine namaha",
  "Om Sarvasvamine namaha",
  "Om Sanatanaya namaha",
  "Om Anantasaktaye namaha",
  "Om Aksobhyaya namaha",
  "Om Parvatipriyanandanaya namaha",
  "Om Gangasutaya namaha",
  "Om Sarodbhutaya namaha",
  "Om Atmabhuve namaha",
  "Om Pavakatmajaya namaha",
  "Om Mayadharaya namaha",
  "Om Prajrimbhaya namaha",
  "Om Ujjrimbhaya namaha",
  "Om Kamalasanasamstutaya namaha",
  "Om Ekavarnaya namaha",
  "Om Dvivarnaya namaha",
  "Om Trivarnaya namaha",
  "Om Sumanoharaya namaha",
  "Om Caturvarnaya namaha",
  "Om Pancavarnaya namaha",
  "Om Prajapataye namaha",
  "Om Trumbaya namaha",
  "Om Agnigarbhaya namaha",
  "Om Samigarbhaya namaha",
  "Om Visvaretase namaha",
  "Om Surarighne namaha",
  "Om Hiranyavarnaya namaha",
  "Om Subhakrite namaha",
  "Om Vasumate namaha",
  "Om Vatuvesabhrite namaha",
  "Om Bhushane namaha",
  "Om Kapastaye namaha",
  "Om Gahanaya namaha",
  "Om Chandravarnaya namaha",
  "Om Kaladharaya namaha",
  "Om Mayadharaya namaha",
  "Om Mahamayine namaha",
  "Om Kaivalyaya namaha",
  "Om Sahatatmakaya namaha",
  "Om Visvayonaye namaha",
  "Om Ameyatmane namaha",
  "Om Tejonidhaye namaha",
  "Om Anamayaya namaha",
  "Om Parameshtine namaha",
  "Om Parabrahmane namaha",
  "Om Vedagarbhaya namaha",
  "Om Viratsutaya namaha",
  "Om Pulindakanyabhartre namaha",
  "Om Mahasarasvatavradaya namaha",
  "Om asrita Kiladhatre namaha",
  "Om Choraghnaya namaha",
  "Om Roganasanaya namaha",
  "Om Anantamurtaye namaha",
  "Om Anandaya namaha",
  "Om Shikhandikritagedanaya namaha",
  "Om Dambhaya namaha",
  "Om Paramadambhaya namaha",
  "Om Mahadambhaya namaha",
  "Om Vrishakapaye namaha",
  "Om Karanopatadehaya namaha",
  "Om Karanatita Vigrahaya namaha",
  "Om Anishvaraya namaha",
  "Om Amritaya namaha",
  "Om Pranaya namaha",
  "Om Pranayamaparayanaya namaha",
  "Om Vritakandare namaha",
  "Om Viraghnaya namaha",
  "Om Raktashyamagalaya namaha",
  "Om Mahate namaha",
  "Om Subrahmanyaya namaha",
  "Om Paravaraya namaha",
  "Om Brahmanyaya namaha",
  "Om Brahmanapriyaya namaha",
  "Om Loka Gurave Namaha",
  "Om Guhapriyaya Namaha",
  "Om Aksayaphalapradaya namaha",
  "Om Valli Devasenasameta Shri Subrahmanyasvamine namaha"
];
