List<String> lordKuberaHindi = [
"ॐ कुबेराय नमः।",
"ॐ धनदाय नमः।",
"ॐ श्रीमाते नमः।",
"ॐ यक्षेशाय नमः।",
"ॐ गुह्यकेश्वराय नमः।",
"ॐ निधीशाय नमः।",
"ॐ शङ्करसखाय नमः।",
"ॐ महालक्ष्मीनिवासभुवये नमः।",
"ॐ महापद्मनिधीशाय नमः।",
"ॐ पूर्णाय नमः।",
"ॐ पद्मनिधीश्वराय नमः।",
"ॐ शङ्ख्यनिधिनाथाय नमः।",
"ॐ मकराख्यनिधिप्रियाय नमः।",
"ॐ सुखसम्पतिनिधीशाय नमः।",
"ॐ मुकुन्दनिधिनायकाय नमः।",
"ॐ कुन्दाक्यनिधिनाथाय नमः।",
"ॐ नीलनित्याधिपाय नमः।",
"ॐ महते नमः।",
"ॐ वरन्नित्याधिपाय नमः।",
"ॐ पूज्याय नमः।",
"ॐ लक्ष्मिसाम्राज्यदायकाय नमः।",
"ॐ इलपिलापतये नमः।",
"ॐ कोशाधीशाय नमः।",
  "ॐ कुलोचिताय नमः।",
"ॐ अश्वारूढाय नमः।",
"ॐ विश्ववन्द्याय नमः।",
"ॐ विशेषज्ञानाय नमः।",
"ॐ विशारदाय नमः।",
"ॐ नलकूबरनाथाय नमः।",
"ॐ मणिग्रीवपित्रे नमः।",
"ॐ गूढमन्त्राय नमः।",
"ॐ वैश्रवणाय नमः।",
"ॐ चित्रलेखामनःप्रियाय नमः।",
"ॐ एकपिनाकाय नमः।",
"ॐ अलकाधीशाय नमः।",
"ॐ पौलस्त्याय नमः।",
"ॐ नरवाहनाय नमः।",
"ॐ कैलासशैलनिलयाय नमः।",
"ॐ राज्यदाय नमः।",
"ॐ रावणाग्रजाय नमः।",
"ॐ चित्रचैत्ररथाय नमः।",
"ॐ उद्यानविहाराय नमः।",
"ॐ विहरसुकुथूहलाय नमः।",
"ॐ महोत्सहाय नमः।",
"ॐ महाप्राज्ञाय नमः।",
"ॐ सदापुष्पक वाहनाय नमः।",
"ॐ सार्वभौमाय नमः।",
"ॐ अङ्गनाथाय नमः।",
"ॐ सोमाय नमः।",
"ॐ सौम्यादिकेश्वराय नमः।",
"ॐ पुण्यात्मने नमः।",
"ॐ पुरूहुतश्रियै नमः।",
"ॐ सर्वपुण्यजनेश्वराय नमः।",
"ॐ नित्यकीर्तये नमः।",
"ॐ निधिवेत्रे नमः।",
"ॐ लंकाप्राक्तन नायकाय नमः।",
"ॐ यक्षिनीवृताय नमः।",
"ॐ यक्षाय नमः।",
"ॐ परमशान्तात्मने नमः।",
"ॐ यक्षराजे नमः।",
"ॐ यक्षिणि हृदयाय नमः।",
"ॐ किन्नरेश्वराय नमः।",
"ॐ किंपुरुशनाथाय नमः।",
"ॐ नाथाय नमः।",
"ॐ खट्कायुधाय नमः।",
"ॐ वशिने नमः।",
"ॐ ईशानदक्ष पार्स्वस्थाय नमः।",
"ॐ वायुवाय समास्रयाय नमः।",
"ॐ धर्ममार्गैस्निरताय नमः।",
"ॐ धर्मसम्मुख संस्थिताय नमः।",
"ॐ नित्येश्वराय नमः।",
"ॐ धनाधयक्षाय नमः।",
"ॐ अष्टलक्ष्म्याश्रितलयाय नमः।",
"ॐ मनुष्य धर्मण्यै नमः।",
"ॐ सकृताय नमः।",
"ॐ कोष लक्ष्मी समाश्रिताय नमः।",
"ॐ धनलक्ष्मी नित्यवासाय नमः।",
"ॐ धान्यलक्ष्मीनिवास भुवये नमः।",
"ॐ अश्तलक्ष्मी सदवासाय नमः।",
"ॐ गजलक्ष्मी स्थिरालयाय नमः।",
"ॐ राज्यलक्ष्मीजन्मगेहाय नमः।",
"ॐ धैर्यलक्ष्मी-कृपाश्रयाय नमः।",
"ॐ अखण्डैश्वर्य संयुक्ताय नमः।",
"ॐ नित्यानन्दाय नमः।",
"ॐ सुखाश्रयाय नमः।",
"ॐ नित्यतृप्ताय नमः।",
"ॐ निधित्तरै नमः।",
"ॐ निराशाय नमः।",
"ॐ निरुपद्रवाय नमः।",
"ॐ नित्यकामाय नमः।",
"ॐ निराकाङ्क्षाय नमः।",
"ॐ निरूपाधिकवासभुवये नमः।",
"ॐ शान्ताय नमः।",
"ॐ सर्वगुणोपेताय नमः।",
"ॐ सर्वज्ञाय नमः।",
"ॐ सर्वसम्मताय नमः।",
"ॐ सर्वाणिकरुणापात्राय नमः।",
"ॐ सदानन्दक्रिपालयाय नमः।",
"ॐ गन्धर्वकुलसंसेव्याय नमः।",
"ॐ सौगन्धिककुसुमप्रियाय नमः।",
"ॐ स्वर्णनगरीवासाय नमः।",
"ॐ निधिपीठ समस्थायै नमः।",
"ॐ महामेरुत्तरस्थायै नमः।",
"ॐ महर्षिगणसंस्तुताय नमः।",
"ॐ तुष्टाय नमः।",
"ॐ शूर्पणकज्येष्ठाय नमः।",
"ॐ शिवपूजारताय नमः।",
"ॐ अनघाय नमः।",
"ॐ राजयोगसमायुक्ताय नमः।",
"ॐ राजसेखरपूज्याय नमः।",
"ॐ राजराजाय नमः।"
];

List<String> lordKuberaEnglish = [
  "Om Kuberaya Namah।",
  "Om Dhanadaya Namah।",
  "Om Shrimate Namah।",
  "Om Yaksheshaya Namah।",
  "Om Guhyakeshvaraya Namah।",
  "Om Nidheeshaya Namah।",
  "Om Shankarasakhaya Namah।",
  "Om Mahalakshmi Nivasabhuvaye Namah।",
  "Om Mahapadma Nidhishaya Namah।",
  "Om Purnaya Namah।",
  "Om Padma Nidhishvaraya Namah।",
  "Om Shankhya Nidhinathaya Namah।",
  "Om Makarakhya Nidhipriyaya Namah।",
  "Om Sukhasampati Nidhishaya Namah।",
  "Om Mukunda Nidhinayakaya Namah।",
  "Om Kundakya Nidhinathaya Namah।",
  "Om Nila Nityadhipaya Namah।",
  "Om Mahate Namah।",
  "Om Varannityadhipaya Namah।",
  "Om Poojyaya Namah।",
  "Om Lakshmisamrajya Dayakaya Namah।",
  "Om Ilapila Pataye Namah।",
  "Om Koshadhishaya Namah।",
  "Om Kulochitaya Namah।",
  "Om Ashvarudhaya Namah।",
  "Om Vishvavandyaya Namah।",
  "Om Visheshagyanaya Namah।",
  "Om Visharadaya Namah।",
  "Om Nalakubara Nathaya Namah।",
  "Om Manigrivapitre Namah।",
  "Om Gudhamantraya Namah।",
  "Om Vaishravanaya Namah।",
  "Om Chitralekhamanah Priyaya Namah।",
  "Om Ekapinakaya Namah।",
  "Om Alakadheeshaya Namah।",
  "Om Paulastyaya Namah।",
  "Om Naravahanaya Namah।",
  "Om Kailasa Shailanilayaya Namah।",
  "Om Rajyadaya Namah।",
  "Om Ravanagrajaya Namah।",
  "Om Chitra Chaitra Rathaya Namah।",
  "Om Udyanaviharaya Namah।",
  "Om Viharasukuthuhalaya Namah।",
  "Om Mahotsahaya Namah।",
  "Om Mahapragyaya Namah।",
  "Om Sadapushpaka Vahanaya Namah।",
  "Om Sarvabhaumaya Namah।",
  "Om Anganathaya Namah।",
  "Om Somaya Namah।",
  "Om Saumyadi Keshvaraya Namah।",
  "Om Punyatmane Namah।",
  "Om Puruhuta Shriyai Namah।",
  "Om Sarvapunya Janeshvaraya Namah।",
  "Om Nityakeertaye Namah।",
  "Om Nidhivetre Namah।",
  "Om Lanka Praktana Nayakaya Namah।",
  "Om Yakshinee Vrutaya Namah।",
  "Om Yakshaya Namah।",
  "Om Parama Shantatmane Namah।",
  "Om Yaksharaje Namah।",
  "Om Yakshini Hrudayaya Namah।",
  "Om Kinnareshvaraya Namah।",
  "Om Kimpurushanathaya Namah।",
  "Om Nathaya Namah।",
  "Om Khatkayudhaya Namah।",
  "Om Vashine Namah।",
  "Om Ishanadaksha Parsvasthaya Namah।",
  "Om Vayuvaya Samasrayaya Namah।",
  "Om Dharma Margaisnirataya Namah।",
  "Om Dharmasammukha Samsthitaya Namah।",
  "Om Nityeshvaraya Namah।",
  "Om Dhanadhayakshaya Namah।",
  "Om Ashtalakshmyashritalayaya Namah।",
  "Om Manushya Dharmanyai Namah।",
  "Om Sakrutaya Namah।",
  "Om Kosha Lakshmi Samashritaya Namah।",
  "Om Dhanalakshmi Nityavasaya Namah।",
  "Om Dhanyalakshminivasa Bhuvaye Namah।",
  "Om Ashtalakshmi Sadavasaya Namah।",
  "Om Gajalakshmi Sthiralayaya Namah।",
  "Om Rajyalakshmi Janmagehaya Namah।",
  "Om Dhairyalakshmi-Krupashrayaya Namah।",
  "Om Akhandaishvarya Samyuktaya Namah।",
  "Om Nityanandaya Namah।",
  "Om Sukhashrayaya Namah।",
  "Om Nityatruptaya Namah।",
  "Om Nidhittarai Namah।",
  "Om Nirashaya Namah।",
  "Om Nirupadravaya Namah।",
  "Om Nityakamaya Namah।",
  "Om Nirakankshaya Namah।",
  "Om Nirupadhika Vasabhuvaye Namah।",
  "Om Shantaya Namah।",
  "Om Sarvagunopetaya Namah।",
  "Om Sarvagyaya Namah।",
  "Om Sarvasammataya Namah।",
  "Om Sarvanikaruna Patraya Namah।",
  "Om Sadanandakripalayaya Namah।",
  "Om Gandharvakula Samsevyaya Namah।",
  "Om Saugandhika Kusumapriyaya Namah।",
  "Om Svarnanagari Vasaya Namah।",
  "Om Nidhipitha Samasthayai Namah।",
  "Om Mahameruttarasthayai Namah।",
  "Om Maharshigana Samstutaya Namah।",
  "Om Tushtaya Namah।",
  "Om Shurpanaka Jyeshthaya Namah।",
  "Om Shivapujarataya Namah।",
  "Om Anaghaya Namah।",
  "Om Rajayoga Samayuktaya Namah।",
  "Om Rajasekhara Poojyaya Namah।",
  "Om Rajarajaya Namah।"

];